DROP SEQUENCE uzytkownicy_seq;
DROP SEQUENCE osoby_seq;
DROP SEQUENCE trasy_seq;
DROP SEQUENCE samoloty_seq;
DROP SEQUENCE reklamacje_seq;
DROP SEQUENCE obce_lotniska_seq;
DROP SEQUENCE modele_seq;
DROP SEQUENCE linie_seq;
DROP SEQUENCE bagaze_seq;
DROP SEQUENCE loty_seq;
DROP SEQUENCE bilety_seq;



CREATE SEQUENCE uzytkownicy_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE osoby_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE obce_lotniska_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE modele_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE samoloty_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE linie_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE trasy_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE reklamacje_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE bagaze_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE bilety_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE loty_seq
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;