/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kamil
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pracownicyButton = new javax.swing.JButton();
        pasazerowieButton = new javax.swing.JButton();
        wyszukajLotButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pracownicyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pracownicyButton.setLabel("Pracownicy");
        pracownicyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pracownicyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pracownicyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 160, 70));
        pracownicyButton.getAccessibleContext().setAccessibleName("pracownicyButton");

        pasazerowieButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pasazerowieButton.setLabel("Pasażerowie");
        pasazerowieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasazerowieButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pasazerowieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 160, 70));
        pasazerowieButton.getAccessibleContext().setAccessibleName("pasazerowieButton");

        wyszukajLotButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        wyszukajLotButton.setLabel("Wyszukaj lot");
        getContentPane().add(wyszukajLotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 240, 110));
        wyszukajLotButton.getAccessibleContext().setAccessibleName("wyszukajLotButton");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PRZYLOTY", "ODLOTY"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 410, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pracownicyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pracownicyButtonActionPerformed
                // TODO add your handling code here:
                new LoginWindow().setVisible(true);
    }//GEN-LAST:event_pracownicyButtonActionPerformed

    private void pasazerowieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasazerowieButtonActionPerformed
                new LoginWindow().setVisible(true);
    }//GEN-LAST:event_pasazerowieButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton pasazerowieButton;
    private javax.swing.JButton pracownicyButton;
    private javax.swing.JButton wyszukajLotButton;
    // End of variables declaration//GEN-END:variables
}
